# Generated by Django 5.1.3 on 2024-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Клиент сервиса",
                "verbose_name_plural": "Клиенты сервиса",
            },
        ),
    ]
