# Generated by Django 5.1.3 on 2024-11-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailing_service", "0001_initial"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
