# Generated by Django 5.1.2 on 2024-11-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0004_alter_mailing_clients_delete_client'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='Сообщение'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]

